apps/mock_forum_web/lib/mock_forum_web/router.ex
defmodule MockForum.Web.Router do
  use MockForum.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MockForum.Web.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MockForum.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/category", CategoryController do
      resources "/thread", ThreadController, except: [:index]
    end

    resources "/profile", ProfileController, except: [:delete], singleton: true
    get "/profile/:id", ProfileController, :profile

    resources "/mailbox", Mailbox.MessageCenterController, except: [:delete]
  end

  scope "/thread/:thread_id", MockForum.Web, as: :thread do
    pipe_through :browser
    resources "/post", PostController
  end

  scope "/auth", MockForum.Web do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
  # Other scopes may use custom stacks.
  # scope "/api", MockForum.Web do
  #   pipe_through :api
  # end
end

apps/mock_forum_web/lib/mock_forum_web/controllers/category_controller.ex
defmodule MockForum.Web.CategoryController do
    @moduledoc """
        Access point for CRUDing Categories
    """

    use MockForum.Web, :controller

    alias MockForum.Category

    def index(conn, _params) do
        render conn, "index.html", categories: Category.all(true)
    end

    def show(conn, %{"id" => category_id}) do
        category =
            category_id
            |> Category.order_by_latest_threads
            |> Repo.one!
        render conn, "show.html", category: category
    end

    def new(conn, _params) do
        render conn, "new.html", changeset: Category.changeset()
    end

    def create(conn, %{"category" => category_params}) do
        case Category.create(category_params) do
            {:ok, _category} ->
                conn
                |> put_flash(:info, "Successfully created a new Category")
                |> redirect(to: page_path(conn, :index))
            {:error, changeset} ->
                conn
                |> put_flash(:error, "Failed to create new Category")
                |> render("new.html", changeset: changeset)
        end
    end

    def edit(conn, %{"id" => category_id}) do
        category  = Category.find!(category_id)
        changeset = Category.changeset(category)

        render conn, "edit.html", changeset: changeset, category: category
    end

    def update(conn, %{"id" => category_id, "category" => category}) do
        case Category.update(category_id, category) do
            {:ok, _category} ->
                conn
                |> put_flash(:info, "successfully edited the category")
                |> redirect(to: page_path(conn, :index))
            {:error, changeset} ->
                conn
                |> put_flash(:error, "There was an error with editing this category")
                |> render("edit.html", changeset: changeset, category: category)
        end
    end

    def delete(conn, %{"id" => category_id}) do
        Category.delete!(category_id)

        conn
        |> put_flash(:info, "Successfully deleted the category")
        |> redirect(to: page_path(conn, :index))
    end
end

apps/mock_forum_web/lib/mock_forum_web/views/category_view.ex
defmodule MockForum.Web.CategoryView do
  use MockForum.Web, :view
end

apps/mock_forum_web/lib/mock_forum_web/templates/category/_form.html.eex
<div class="form-group">
    <%= text_input @f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag @f, :title %>

    <%= text_input @f, :description, placeholder: "Description", class: "form-control" %>
    <%= error_tag @f, :description %>

    <%= submit "Submit", class: "btn btn-primary" %>
</div>

apps/mock_forum_web/lib/mock_forum_web/templates/category/edit.html.eex
<%= form_for @changeset, category_path(@conn, :update, @category), fn f -> %>
    <%= render MockForum.Web.CategoryView, "_form.html", f: f %>
<% end %>

apps/mock_forum_web/lib/mock_forum_web/templates/category/new.html.eex
<%= form_for @changeset, category_path(@conn, :create), fn f -> %>
    <%= render MockForum.Web.CategoryView, "_form.html", f: f %>
<% end %>

apps/mock_forum_web/lib/mock_forum_web/templates/category/show.html.eex
<h3><%= @category.title %></h3>
<%= link("Edit", to: category_path(@conn, :edit, @category), class: "btn-sm btn-primary") %>

<br/><br/>

<table class="table table-striped" cellspacing="0", width="100%">
  <thead>
    <tr>
      <th></th>
      <th>Last Updated</th>
      <th><%= link("New Thread", to: category_thread_path(@conn, :new, @category.id), class: "btn-sm btn-success") %></th>
    </tr>
  </thead>
  <tbody>
    <%= for thread <- @category.threads do %>
      <%= for post <- thread.posts do %>
        <tr>
          <td><%= link(thread.title, to: thread_post_path(@conn, :index, thread)) %></td>
          <td><%= format_time_standard(post.updated_at) %></td>
          <td>
              <ul>
                  <li>By <%= post.user.first_name %></li>
                  <li><%= format_time_standard(post.inserted_at) %></li>
              </ul>
          </td>
          <td><%= link("Delete", to: category_thread_path(@conn, :delete, @category, thread), method: :delete) %></td>
        </tr>
      <% end %>
  <% end %>

  </tbody>
</table>