apps/mock_forum_web/lib/mock_forum_web/router.ex
defmodule MockForum.Web.Router do
  use MockForum.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MockForum.Web.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MockForum.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/category", CategoryController do
      resources "/thread", ThreadController, except: [:index]
    end

    resources "/profile", ProfileController, except: [:delete], singleton: true
    get "/profile/:id", ProfileController, :profile

    resources "/mailbox", Mailbox.MessageCenterController, except: [:delete]
  end

  scope "/thread/:thread_id", MockForum.Web, as: :thread do
    pipe_through :browser
    resources "/post", PostController
  end

  scope "/auth", MockForum.Web do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
  # Other scopes may use custom stacks.
  # scope "/api", MockForum.Web do
  #   pipe_through :api
  # end
end

apps/mock_forum_web/lib/mock_forum_web/views/layout_view.ex
defmodule MockForum.Web.LayoutView do
  use MockForum.Web, :view
end

apps/mock_forum_web/lib/mock_forum_web/templates/layout/_header.html.eex
<div id="header-wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><%= link("Phx 1.3 Mock Forum", to: page_path(@conn, :index)) %></h1>
		</div>
		<div id="menu">
			<ul>
				<li class="current_page_item">
                     <%= link("Homepage", to: page_path(@conn, :index), accesskey: "1") %>
                </li>
				<%= if @conn.assigns[:user] do %>
					<li>
						<%= link("Profile", to: profile_path(@conn, :show), accesskey: "2") %>
					</li>
				<% end %>
				<li>
                    <%= if @conn.assigns[:user] do %>
                        <%= link("Signout", to: auth_path(@conn, :signout) , accesskey: "3") %>
                    <% else %>
                        <%= link("Login With Github", to: auth_path(@conn, :request, "github") , accesskey: "2") %>
                    <% end %>
                </li>
			</ul>
		</div>
	</div>
</div>

apps/mock_forum_web/lib/mock_forum_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello MockForum!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/timeline.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/font.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/timeline.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/title_card.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/chat.css") %>">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800" rel="stylesheet" />
  </head>

  <body>
    <%= render MockForum.Web.LayoutView, "_header.html", conn: @conn %>
    <div id="featured">&nbsp;</div>
    <div id="wrapper">
      <div id="page" class="container">

        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>


        <div id="content">
          <main role="main">
            <%= render @view_module, @view_template, assigns %>
          </main>
        </div>
      </div> <!-- /container -->
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>