apps/mock_forum_web/lib/mock_forum_web/router.ex
defmodule MockForum.Web.Router do
  use MockForum.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MockForum.Web.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MockForum.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/category", CategoryController do
      resources "/thread", ThreadController, except: [:index]
    end

    resources "/profile", ProfileController, except: [:delete], singleton: true
    get "/profile/:id", ProfileController, :profile

    resources "/mailbox", Mailbox.MessageCenterController, except: [:delete]
  end

  scope "/thread/:thread_id", MockForum.Web, as: :thread do
    pipe_through :browser
    resources "/post", PostController
  end

  scope "/auth", MockForum.Web do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
  # Other scopes may use custom stacks.
  # scope "/api", MockForum.Web do
  #   pipe_through :api
  # end
end

apps/mock_forum_web/lib/mock_forum_web/controllers/profile_controller.ex
defmodule MockForum.Web.ProfileController do
    @moduledoc """
        Access point for CRUDing posts
    """

    use MockForum.Web, :controller
    plug MockForum.Web.Plugs.RequireAuth

    alias MockForum.{User, UserDecorator}

    def profile(conn, %{"id" => user_id}) do
        user =
            user_id
            |> User.find!
            |> UserDecorator.decorate

        render(conn, "profile.html", user: user)
    end

    def show(conn, _params) do
        user = UserDecorator.decorate(conn.assigns.user)
        render conn, "show.html", user: user
    end

    def edit(conn, _params) do
        changeset = User.changeset(conn.assigns.user)
        render conn, "edit.html", changeset: changeset
    end

    def update(conn, %{"user" => user}) do
        case User.update(conn.assigns.user.id, user) do
            {:ok, _user} ->
                conn
                |> put_flash(:info, "Successfully updated your profile")
                |> redirect(to: profile_path(conn, :show))
            {:error, changeset} ->
                conn
                |> put_flash(:error, "There was an error with editing your profile")
                |> render("edit.html", changeset: changeset)
        end
    end
end

apps/mock_forum_web/lib/mock_forum_web/views/profile_view.ex
defmodule MockForum.Web.ProfileView do
  use MockForum.Web, :view
end

apps/mock_forum_web/lib/mock_forum_web/templates/profile/_basic_profile.html.eex
<ul>
    <li><%= profile_icon(@user) %></li>
    <li>Name: <%= @user.profile_name %></li>
    <li>Email: <%= @user.email %></li>
    <li>Authorized By: <%= @user.provider %></li>
    <li>Has posted: <%= @user.post_count %> time/s</li>
</ul>

apps/mock_forum_web/lib/mock_forum_web/templates/profile/edit.html.eex
<%= form_for @changeset, profile_path(@conn, :update), [multipart: true], fn f -> %>
  <div class="form-group">
    <label>Photo</label>
    <%= file_input f, :avatar, accept: "image/*", class: "form-control" %>
    <%= error_tag f, :avatar %>
  </div>

    <div class="form-group">
        <%= textarea f, :first_name, placeholder: "Message", class: "form-control" %>
        <%= error_tag f, :first_name %>
    </div>
    <div class="form-group">
        <%= textarea f, :last_name, placeholder: "Message", class: "form-control" %>
        <%= error_tag f, :first_name %>

        <%= submit "Submit", class: "btn btn-primary" %>
    </div>
<% end %>

apps/mock_forum_web/lib/mock_forum_web/templates/profile/profile.html.eex
<%= link("Private Message ME!", to: message_center_path(@conn, :new, receipient_id: @user.id)) %>
<%= render MockForum.Web.ProfileView, "_basic_profile.html", user: @user %>

apps/mock_forum_web/lib/mock_forum_web/templates/profile/show.html.eex
<%= link "Edit Profile", to: profile_path(@conn, :edit), class: "btn-sm btn-success" %>
<%= render MockForum.Web.ProfileView, "_basic_profile.html", user: @user %>